from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

from Student import Etudiant

class Ui_Dialog(object):
    def ajouter(self):
        numInsc=self.lineEditNumeroInscription.text()
        nom=self.lineEditNom.text()
        prenom=self.lineEditPrenom.text()
        date=self.DateNaissance.selectedDate().toString()
        adresse=self.lineEditAdresse.text()
        mail=self.lineEditMail.text()
        telephone=self.lineEditTelephone.text()
        section=self.lineEditSection.text()
        niveau=self.lineEditNiveauEtude.text()

        self.ISIMM.afficherEtudiants()
        self.ISIMM.ajouterEtudiant(Etudiant(numInsc,nom,prenom,date,adresse,mail,telephone,section,niveau))
        self.ISIMM.afficherEtudiants()
        
    def __init__(self,ISIMM):
        self.ISIMM=ISIMM
    def showDialog(self,str):
        msgBox = QMessageBox()
        msgBox.setIcon(QMessageBox.Warning)
        msgBox.setText(str)
        msgBox.setWindowTitle("Msg Error")
        msgBox.setStandardButtons(QMessageBox.Ok)
        msgBox.exec()
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(949, 782)
        Dialog.setStyleSheet("background-color:#A9A9A9;")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(230, 100, 161, 21))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.lineEditNumeroInscription = QtWidgets.QLineEdit(Dialog)
        self.lineEditNumeroInscription.setGeometry(QtCore.QRect(400, 100, 321, 30))
        self.lineEditNumeroInscription.setObjectName("lineEditNumeroInscription")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(230, 150, 161, 21))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.lineEditNom = QtWidgets.QLineEdit(Dialog)
        self.lineEditNom.setGeometry(QtCore.QRect(400, 150, 321, 30))
        self.lineEditNom.setObjectName("lineEditNom")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(230, 200, 161, 21))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.lineEditPrenom = QtWidgets.QLineEdit(Dialog)
        self.lineEditPrenom.setGeometry(QtCore.QRect(400, 200, 321, 30))
        self.lineEditPrenom.setObjectName("lineEditPrenom")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(230, 270, 161, 21))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.DateNaissance = QtWidgets.QCalendarWidget(Dialog)
        self.DateNaissance.setGeometry(QtCore.QRect(400, 240, 321, 191))
        self.DateNaissance.setGridVisible(True)
        self.DateNaissance.setObjectName("DateNaissance")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(230, 450, 161, 21))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(230, 500, 161, 21))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.lineEditAdresse = QtWidgets.QLineEdit(Dialog)
        self.lineEditAdresse.setGeometry(QtCore.QRect(400, 450, 321, 30))
        self.lineEditAdresse.setObjectName("lineEditAdresse")
        self.lineEditMail = QtWidgets.QLineEdit(Dialog)
        self.lineEditMail.setGeometry(QtCore.QRect(400, 500, 321, 30))
        self.lineEditMail.setObjectName("lineEditMail")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(230, 550, 161, 21))
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.lineEditTelephone = QtWidgets.QLineEdit(Dialog)
        self.lineEditTelephone.setGeometry(QtCore.QRect(400, 550, 321, 30))
        self.lineEditTelephone.setObjectName("lineEditTelephone")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(230, 600, 161, 21))
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(230, 650, 161, 21))
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.lineEditSection = QtWidgets.QLineEdit(Dialog)
        self.lineEditSection.setGeometry(QtCore.QRect(400, 600, 321, 30))
        self.lineEditSection.setObjectName("lineEditSection")
        self.lineEditNiveauEtude = QtWidgets.QLineEdit(Dialog)
        self.lineEditNiveauEtude.setGeometry(QtCore.QRect(400, 650, 321, 30))
        self.lineEditNiveauEtude.setObjectName("lineEditNiveauEtude")
        self.Ajouter = QtWidgets.QPushButton(Dialog)
        self.Ajouter.setGeometry(QtCore.QRect(350, 710, 251, 31))
        self.Ajouter.setObjectName("Ajouter")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(350, 30, 251, 41))
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setStyleSheet("font: 75 22pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.Ajouter.clicked.connect(self.ajouter)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Numéro d\'inscription"))
        self.label_2.setText(_translate("Dialog", "Nom"))
        self.label_3.setText(_translate("Dialog", "Prénom"))
        self.label_4.setText(_translate("Dialog", "Date de naissance"))
        self.label_5.setText(_translate("Dialog", "Adresse"))
        self.label_6.setText(_translate("Dialog", "Mail"))
        self.label_7.setText(_translate("Dialog", "Téléphone"))
        self.label_8.setText(_translate("Dialog", "Section"))
        self.label_9.setText(_translate("Dialog", "Niveau d\'étude"))
        self.Ajouter.setText(_translate("Dialog", "Ajouter"))
        self.label_10.setText(_translate("Dialog", "Ajouter un étudiant"))
