from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from AddStudent import Ui_Dialog

class Ui_MainWindow(object):

    def ajouterEtudiant(self):
        self.windowAjouter=QDialog()
        self.ui=Ui_Dialog(self.ISIMM)
        self.ui.setupUi(self.windowAjouter)
        self.windowAjouter.show()

    def __init__(self,ISIMM):
        self.ISIMM=ISIMM
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 787)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("font: 75 12pt \"Arial\";background-color:#A09FA0;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 24))
        self.menubar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.menubar.setAutoFillBackground(False)
        self.menubar.setStyleSheet("background-color:#777477;")
        self.menubar.setObjectName("menubar")
        self.menuGestion_des_etudiants = QtWidgets.QMenu(self.menubar)
        self.menuGestion_des_etudiants.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.menuGestion_des_etudiants.setStyleSheet("margin:5px; ")
        self.menuGestion_des_etudiants.setObjectName("menuGestion_des_etudiants")
        self.menuMise_jour_des_etudiants = QtWidgets.QMenu(self.menuGestion_des_etudiants)
        self.menuMise_jour_des_etudiants.setObjectName("menuMise_jour_des_etudiants")
        self.menuModifier_etudiant = QtWidgets.QMenu(self.menuMise_jour_des_etudiants)
        self.menuModifier_etudiant.setObjectName("menuModifier_etudiant")
        self.menuSupprimer_etudiant = QtWidgets.QMenu(self.menuMise_jour_des_etudiants)
        self.menuSupprimer_etudiant.setObjectName("menuSupprimer_etudiant")
        self.menuRecherche_Affichage = QtWidgets.QMenu(self.menuGestion_des_etudiants)
        self.menuRecherche_Affichage.setObjectName("menuRecherche_Affichage")
        self.menuGestion_des_matieres = QtWidgets.QMenu(self.menubar)
        self.menuGestion_des_matieres.setStyleSheet("margin:5px; ")
        self.menuGestion_des_matieres.setObjectName("menuGestion_des_matieres")
        self.menuMise_jour = QtWidgets.QMenu(self.menuGestion_des_matieres)
        self.menuMise_jour.setObjectName("menuMise_jour")
        self.menuModifier_les_donnees_dune_matiere = QtWidgets.QMenu(self.menuMise_jour)
        self.menuModifier_les_donnees_dune_matiere.setObjectName("menuModifier_les_donnees_dune_matiere")
        self.menuRecherche_Affiche = QtWidgets.QMenu(self.menuGestion_des_matieres)
        self.menuRecherche_Affiche.setObjectName("menuRecherche_Affiche")
        self.menuGestion_des_notes = QtWidgets.QMenu(self.menubar)
        self.menuGestion_des_notes.setStyleSheet("margin:5px; ")
        self.menuGestion_des_notes.setObjectName("menuGestion_des_notes")
        self.menuMise_jour_2 = QtWidgets.QMenu(self.menuGestion_des_notes)
        self.menuMise_jour_2.setObjectName("menuMise_jour_2")
        self.menuRecherche_Affichage_2 = QtWidgets.QMenu(self.menuGestion_des_notes)
        self.menuRecherche_Affichage_2.setObjectName("menuRecherche_Affichage_2")
        self.menuCalcul_et_Affichage = QtWidgets.QMenu(self.menubar)
        self.menuCalcul_et_Affichage.setStyleSheet("margin:5px; ")
        self.menuCalcul_et_Affichage.setObjectName("menuCalcul_et_Affichage")
        self.menuEnregistrement_et_recuperation = QtWidgets.QMenu(self.menubar)
        self.menuEnregistrement_et_recuperation.setStyleSheet("margin:5px; ")
        self.menuEnregistrement_et_recuperation.setObjectName("menuEnregistrement_et_recuperation")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAjouter_etudiant = QtWidgets.QAction(MainWindow)
        self.actionAjouter_etudiant.setObjectName("actionAjouter_etudiant")
        self.actionSuppression_etudiant_donn = QtWidgets.QAction(MainWindow)
        self.actionSuppression_etudiant_donn.setObjectName("actionSuppression_etudiant_donn")
        self.actionSuppression_des_etudiants_d_une_section_donn_e = QtWidgets.QAction(MainWindow)
        self.actionSuppression_des_etudiants_d_une_section_donn_e.setObjectName("actionSuppression_des_etudiants_d_une_section_donn_e")
        self.actionSuppression_des_etudiants_d_un_niveau_donn = QtWidgets.QAction(MainWindow)
        self.actionSuppression_des_etudiants_d_un_niveau_donn.setObjectName("actionSuppression_des_etudiants_d_un_niveau_donn")
        self.actionSuppression_des_etudiants_d_une_section_et_un_niveau = QtWidgets.QAction(MainWindow)
        self.actionSuppression_des_etudiants_d_une_section_et_un_niveau.setObjectName("actionSuppression_des_etudiants_d_une_section_et_un_niveau")
        self.actionT_l_phone = QtWidgets.QAction(MainWindow)
        self.actionT_l_phone.setObjectName("actionT_l_phone")
        self.actionMail = QtWidgets.QAction(MainWindow)
        self.actionMail.setObjectName("actionMail")
        self.actionAdresse = QtWidgets.QAction(MainWindow)
        self.actionAdresse.setObjectName("actionAdresse")
        self.actionAfficher_les_etudiants = QtWidgets.QAction(MainWindow)
        self.actionAfficher_les_etudiants.setObjectName("actionAfficher_les_etudiants")
        self.actionRecherche_par_numero_d_inscription = QtWidgets.QAction(MainWindow)
        self.actionRecherche_par_numero_d_inscription.setObjectName("actionRecherche_par_numero_d_inscription")
        self.actionRecherche_par_section_etudiant = QtWidgets.QAction(MainWindow)
        self.actionRecherche_par_section_etudiant.setObjectName("actionRecherche_par_section_etudiant")
        self.actionRecherche_par_section_et_niveau = QtWidgets.QAction(MainWindow)
        self.actionRecherche_par_section_et_niveau.setObjectName("actionRecherche_par_section_et_niveau")
        self.actionRecherche_par_niveau = QtWidgets.QAction(MainWindow)
        self.actionRecherche_par_niveau.setObjectName("actionRecherche_par_niveau")
        self.actionAjouter_une_matiere = QtWidgets.QAction(MainWindow)
        self.actionAjouter_une_matiere.setObjectName("actionAjouter_une_matiere")
        self.actionSupprimer_une_matiere = QtWidgets.QAction(MainWindow)
        self.actionSupprimer_une_matiere.setObjectName("actionSupprimer_une_matiere")
        self.actionNom = QtWidgets.QAction(MainWindow)
        self.actionNom.setObjectName("actionNom")
        self.actionCoefficient = QtWidgets.QAction(MainWindow)
        self.actionCoefficient.setObjectName("actionCoefficient")
        self.actionAfficher_les_matieres = QtWidgets.QAction(MainWindow)
        self.actionAfficher_les_matieres.setObjectName("actionAfficher_les_matieres")
        self.actionRecherche_par_code = QtWidgets.QAction(MainWindow)
        self.actionRecherche_par_code.setObjectName("actionRecherche_par_code")
        self.actionRecherche_par_section_matiere = QtWidgets.QAction(MainWindow)
        self.actionRecherche_par_section_matiere.setObjectName("actionRecherche_par_section_matiere")
        self.actionRecherche_par_section_et_semestre = QtWidgets.QAction(MainWindow)
        self.actionRecherche_par_section_et_semestre.setObjectName("actionRecherche_par_section_et_semestre")
        self.actionAjouter_une_note = QtWidgets.QAction(MainWindow)
        self.actionAjouter_une_note.setObjectName("actionAjouter_une_note")
        self.actionSupprimer_une_note = QtWidgets.QAction(MainWindow)
        self.actionSupprimer_une_note.setObjectName("actionSupprimer_une_note")
        self.actionModifier_une_note = QtWidgets.QAction(MainWindow)
        self.actionModifier_une_note.setObjectName("actionModifier_une_note")
        self.actionAffiche_les_notes = QtWidgets.QAction(MainWindow)
        self.actionAffiche_les_notes.setObjectName("actionAffiche_les_notes")
        self.actionRecherche_par_num_ro_d_inscription_2 = QtWidgets.QAction(MainWindow)
        self.actionRecherche_par_num_ro_d_inscription_2.setObjectName("actionRecherche_par_num_ro_d_inscription_2")
        self.actionRecherche_par_section_et_niveau_2 = QtWidgets.QAction(MainWindow)
        self.actionRecherche_par_section_et_niveau_2.setObjectName("actionRecherche_par_section_et_niveau_2")
        self.actionRecherche_par_num_ro_d_inscription_et_semestre = QtWidgets.QAction(MainWindow)
        self.actionRecherche_par_num_ro_d_inscription_et_semestre.setObjectName("actionRecherche_par_num_ro_d_inscription_et_semestre")
        self.actionBulletin_de_note_d_un_etudiant = QtWidgets.QAction(MainWindow)
        self.actionBulletin_de_note_d_un_etudiant.setObjectName("actionBulletin_de_note_d_un_etudiant")
        self.actionBulletin_de_note_d_un_tudiant_par_semestre = QtWidgets.QAction(MainWindow)
        self.actionBulletin_de_note_d_un_tudiant_par_semestre.setObjectName("actionBulletin_de_note_d_un_tudiant_par_semestre")
        self.actionEtudiants_admis_d_une_section_donnee = QtWidgets.QAction(MainWindow)
        self.actionEtudiants_admis_d_une_section_donnee.setObjectName("actionEtudiants_admis_d_une_section_donnee")
        self.actionEtudiants_redoublants_d_une_section_donnee = QtWidgets.QAction(MainWindow)
        self.actionEtudiants_redoublants_d_une_section_donnee.setObjectName("actionEtudiants_redoublants_d_une_section_donnee")
        self.actionEtudiants_admis_de_l_ISIMM = QtWidgets.QAction(MainWindow)
        self.actionEtudiants_admis_de_l_ISIMM.setObjectName("actionEtudiants_admis_de_l_ISIMM")
        self.actionEtudiants_redoublants_de_l_ISIMM = QtWidgets.QAction(MainWindow)
        self.actionEtudiants_redoublants_de_l_ISIMM.setObjectName("actionEtudiants_redoublants_de_l_ISIMM")
        self.actionMoyennes_des_etudiants_d_une_section_donnee = QtWidgets.QAction(MainWindow)
        self.actionMoyennes_des_etudiants_d_une_section_donnee.setObjectName("actionMoyennes_des_etudiants_d_une_section_donnee")
        self.actionEnregistrement_fichier_Etudiants = QtWidgets.QAction(MainWindow)
        self.actionEnregistrement_fichier_Etudiants.setObjectName("actionEnregistrement_fichier_Etudiants")
        self.actionRecuperation_fichier_Etudiants = QtWidgets.QAction(MainWindow)
        self.actionRecuperation_fichier_Etudiants.setObjectName("actionRecuperation_fichier_Etudiants")
        self.actionEnregistrement_fichier_Matieres = QtWidgets.QAction(MainWindow)
        self.actionEnregistrement_fichier_Matieres.setObjectName("actionEnregistrement_fichier_Matieres")
        self.actionRecuperation_fichier_Matieres = QtWidgets.QAction(MainWindow)
        self.actionRecuperation_fichier_Matieres.setObjectName("actionRecuperation_fichier_Matieres")
        self.actionEnregistrement_fichier_Notes = QtWidgets.QAction(MainWindow)
        self.actionEnregistrement_fichier_Notes.setObjectName("actionEnregistrement_fichier_Notes")
        self.actionRecuperation_fichier_Notes = QtWidgets.QAction(MainWindow)
        self.actionRecuperation_fichier_Notes.setObjectName("actionRecuperation_fichier_Notes")
        self.menuModifier_etudiant.addAction(self.actionT_l_phone)
        self.menuModifier_etudiant.addSeparator()
        self.menuModifier_etudiant.addAction(self.actionMail)
        self.menuModifier_etudiant.addSeparator()
        self.menuModifier_etudiant.addAction(self.actionAdresse)
        self.menuModifier_etudiant.addSeparator()
        self.menuSupprimer_etudiant.addAction(self.actionSuppression_etudiant_donn)
        self.menuSupprimer_etudiant.addSeparator()
        self.menuSupprimer_etudiant.addAction(self.actionSuppression_des_etudiants_d_une_section_donn_e)
        self.menuSupprimer_etudiant.addSeparator()
        self.menuSupprimer_etudiant.addAction(self.actionSuppression_des_etudiants_d_un_niveau_donn)
        self.menuSupprimer_etudiant.addSeparator()
        self.menuSupprimer_etudiant.addAction(self.actionSuppression_des_etudiants_d_une_section_et_un_niveau)
        self.menuSupprimer_etudiant.addSeparator()
        self.menuMise_jour_des_etudiants.addAction(self.actionAjouter_etudiant)
        self.menuMise_jour_des_etudiants.addSeparator()
        self.menuMise_jour_des_etudiants.addAction(self.menuSupprimer_etudiant.menuAction())
        self.menuMise_jour_des_etudiants.addSeparator()
        self.menuMise_jour_des_etudiants.addAction(self.menuModifier_etudiant.menuAction())
        self.menuMise_jour_des_etudiants.addSeparator()
        self.menuRecherche_Affichage.addAction(self.actionAfficher_les_etudiants)
        self.menuRecherche_Affichage.addSeparator()
        self.menuRecherche_Affichage.addAction(self.actionRecherche_par_numero_d_inscription)
        self.menuRecherche_Affichage.addSeparator()
        self.menuRecherche_Affichage.addAction(self.actionRecherche_par_section_etudiant)
        self.menuRecherche_Affichage.addSeparator()
        self.menuRecherche_Affichage.addAction(self.actionRecherche_par_niveau)
        self.menuRecherche_Affichage.addSeparator()
        self.menuRecherche_Affichage.addAction(self.actionRecherche_par_section_et_niveau)
        self.menuRecherche_Affichage.addSeparator()
        self.menuGestion_des_etudiants.addAction(self.menuMise_jour_des_etudiants.menuAction())
        self.menuGestion_des_etudiants.addSeparator()
        self.menuGestion_des_etudiants.addAction(self.menuRecherche_Affichage.menuAction())
        self.menuGestion_des_etudiants.addSeparator()
        self.menuModifier_les_donnees_dune_matiere.addAction(self.actionNom)
        self.menuModifier_les_donnees_dune_matiere.addSeparator()
        self.menuModifier_les_donnees_dune_matiere.addAction(self.actionCoefficient)
        self.menuModifier_les_donnees_dune_matiere.addSeparator()
        self.menuMise_jour.addAction(self.actionAjouter_une_matiere)
        self.menuMise_jour.addSeparator()
        self.menuMise_jour.addAction(self.actionSupprimer_une_matiere)
        self.menuMise_jour.addSeparator()
        self.menuMise_jour.addAction(self.menuModifier_les_donnees_dune_matiere.menuAction())
        self.menuMise_jour.addSeparator()
        self.menuRecherche_Affiche.addAction(self.actionAfficher_les_matieres)
        self.menuRecherche_Affiche.addSeparator()
        self.menuRecherche_Affiche.addAction(self.actionRecherche_par_code)
        self.menuRecherche_Affiche.addSeparator()
        self.menuRecherche_Affiche.addAction(self.actionRecherche_par_section_matiere)
        self.menuRecherche_Affiche.addSeparator()
        self.menuRecherche_Affiche.addAction(self.actionRecherche_par_section_et_semestre)
        self.menuRecherche_Affiche.addSeparator()
        self.menuGestion_des_matieres.addAction(self.menuMise_jour.menuAction())
        self.menuGestion_des_matieres.addSeparator()
        self.menuGestion_des_matieres.addAction(self.menuRecherche_Affiche.menuAction())
        self.menuGestion_des_matieres.addSeparator()
        self.menuMise_jour_2.addAction(self.actionAjouter_une_note)
        self.menuMise_jour_2.addSeparator()
        self.menuMise_jour_2.addAction(self.actionSupprimer_une_note)
        self.menuMise_jour_2.addSeparator()
        self.menuMise_jour_2.addAction(self.actionModifier_une_note)
        self.menuMise_jour_2.addSeparator()
        self.menuRecherche_Affichage_2.addAction(self.actionAffiche_les_notes)
        self.menuRecherche_Affichage_2.addSeparator()
        self.menuRecherche_Affichage_2.addAction(self.actionRecherche_par_num_ro_d_inscription_2)
        self.menuRecherche_Affichage_2.addSeparator()
        self.menuRecherche_Affichage_2.addAction(self.actionRecherche_par_section_et_niveau_2)
        self.menuRecherche_Affichage_2.addSeparator()
        self.menuRecherche_Affichage_2.addAction(self.actionRecherche_par_num_ro_d_inscription_et_semestre)
        self.menuRecherche_Affichage_2.addSeparator()
        self.menuGestion_des_notes.addAction(self.menuMise_jour_2.menuAction())
        self.menuGestion_des_notes.addSeparator()
        self.menuGestion_des_notes.addAction(self.menuRecherche_Affichage_2.menuAction())
        self.menuGestion_des_notes.addSeparator()
        self.menuCalcul_et_Affichage.addAction(self.actionBulletin_de_note_d_un_etudiant)
        self.menuCalcul_et_Affichage.addSeparator()
        self.menuCalcul_et_Affichage.addAction(self.actionBulletin_de_note_d_un_tudiant_par_semestre)
        self.menuCalcul_et_Affichage.addSeparator()
        self.menuCalcul_et_Affichage.addAction(self.actionEtudiants_admis_d_une_section_donnee)
        self.menuCalcul_et_Affichage.addSeparator()
        self.menuCalcul_et_Affichage.addAction(self.actionEtudiants_redoublants_d_une_section_donnee)
        self.menuCalcul_et_Affichage.addSeparator()
        self.menuCalcul_et_Affichage.addAction(self.actionEtudiants_admis_de_l_ISIMM)
        self.menuCalcul_et_Affichage.addSeparator()
        self.menuCalcul_et_Affichage.addAction(self.actionEtudiants_redoublants_de_l_ISIMM)
        self.menuCalcul_et_Affichage.addSeparator()
        self.menuCalcul_et_Affichage.addAction(self.actionMoyennes_des_etudiants_d_une_section_donnee)
        self.menuCalcul_et_Affichage.addSeparator()
        self.menuEnregistrement_et_recuperation.addAction(self.actionEnregistrement_fichier_Etudiants)
        self.menuEnregistrement_et_recuperation.addSeparator()
        self.menuEnregistrement_et_recuperation.addAction(self.actionRecuperation_fichier_Etudiants)
        self.menuEnregistrement_et_recuperation.addSeparator()
        self.menuEnregistrement_et_recuperation.addAction(self.actionEnregistrement_fichier_Matieres)
        self.menuEnregistrement_et_recuperation.addSeparator()
        self.menuEnregistrement_et_recuperation.addAction(self.actionRecuperation_fichier_Matieres)
        self.menuEnregistrement_et_recuperation.addSeparator()
        self.menuEnregistrement_et_recuperation.addAction(self.actionEnregistrement_fichier_Notes)
        self.menuEnregistrement_et_recuperation.addSeparator()
        self.menuEnregistrement_et_recuperation.addAction(self.actionRecuperation_fichier_Notes)
        self.menubar.addAction(self.menuGestion_des_etudiants.menuAction())
        self.menubar.addAction(self.menuGestion_des_matieres.menuAction())
        self.menubar.addAction(self.menuGestion_des_notes.menuAction())
        self.menubar.addAction(self.menuCalcul_et_Affichage.menuAction())
        self.menubar.addAction(self.menuEnregistrement_et_recuperation.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



        self.actionAjouter_etudiant.triggered.connect(self.ajouterEtudiant)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuGestion_des_etudiants.setTitle(_translate("MainWindow", "Gestion des etudiants"))
        self.menuMise_jour_des_etudiants.setTitle(_translate("MainWindow", "Mise à jour des étudiants"))
        self.menuModifier_etudiant.setTitle(_translate("MainWindow", "Modifier étudiant"))
        self.menuSupprimer_etudiant.setTitle(_translate("MainWindow", "Supprimer étudiant"))
        self.menuRecherche_Affichage.setTitle(_translate("MainWindow", "Recherche , Affichage"))
        self.menuGestion_des_matieres.setTitle(_translate("MainWindow", "Gestion des matiéres"))
        self.menuMise_jour.setTitle(_translate("MainWindow", "Mise à jour"))
        self.menuModifier_les_donnees_dune_matiere.setTitle(_translate("MainWindow", "Modifier une matière"))
        self.menuRecherche_Affiche.setTitle(_translate("MainWindow", "Recherche , Affichage"))
        self.menuGestion_des_notes.setTitle(_translate("MainWindow", "Gestion des notes"))
        self.menuMise_jour_2.setTitle(_translate("MainWindow", "Mise à jour"))
        self.menuRecherche_Affichage_2.setTitle(_translate("MainWindow", "Recherche , Affichage"))
        self.menuCalcul_et_Affichage.setTitle(_translate("MainWindow", "Calcul et Affichage"))
        self.menuEnregistrement_et_recuperation.setTitle(_translate("MainWindow", "Enregistrement et récupération"))
        self.actionAjouter_etudiant.setText(_translate("MainWindow", "Ajouter étudiant"))
        self.actionSuppression_etudiant_donn.setText(_translate("MainWindow", "Suppression étudiant donné"))
        self.actionSuppression_des_etudiants_d_une_section_donn_e.setText(_translate("MainWindow", "Suppression des étudiants d\'une section donnée"))
        self.actionSuppression_des_etudiants_d_un_niveau_donn.setText(_translate("MainWindow", "Suppression des étudiants d\'un niveau donné"))
        self.actionSuppression_des_etudiants_d_une_section_et_un_niveau.setText(_translate("MainWindow", "Suppression des étudiants d\'une section et un niveau "))
        self.actionT_l_phone.setText(_translate("MainWindow", "Téléphone"))
        self.actionMail.setText(_translate("MainWindow", "Mail"))
        self.actionAdresse.setText(_translate("MainWindow", "Adresse"))
        self.actionAfficher_les_etudiants.setText(_translate("MainWindow", "Afficher les étudiants"))
        self.actionRecherche_par_numero_d_inscription.setText(_translate("MainWindow", "Recherche par numéro d\'inscription"))
        self.actionRecherche_par_section_etudiant.setText(_translate("MainWindow", "Recherche par section"))
        self.actionRecherche_par_section_et_niveau.setText(_translate("MainWindow", "Recherche par section et niveau"))
        self.actionRecherche_par_niveau.setText(_translate("MainWindow", "Recherche par niveau"))
        self.actionAjouter_une_matiere.setText(_translate("MainWindow", "Ajouter une matiére"))
        self.actionSupprimer_une_matiere.setText(_translate("MainWindow", "Supprimer une matière"))
        self.actionNom.setText(_translate("MainWindow", "Nom"))
        self.actionCoefficient.setText(_translate("MainWindow", "Coefficient"))
        self.actionAfficher_les_matieres.setText(_translate("MainWindow", "Afficher les matières"))
        self.actionRecherche_par_code.setText(_translate("MainWindow", "Recherche par code"))
        self.actionRecherche_par_section_matiere.setText(_translate("MainWindow", "Recherche par section"))
        self.actionRecherche_par_section_et_semestre.setText(_translate("MainWindow", "Recherche par section et semestre"))
        self.actionAjouter_une_note.setText(_translate("MainWindow", "Ajouter une note"))
        self.actionSupprimer_une_note.setText(_translate("MainWindow", "Supprimer une note"))
        self.actionModifier_une_note.setText(_translate("MainWindow", "Modifier une note"))
        self.actionAffiche_les_notes.setText(_translate("MainWindow", "Affiche les notes"))
        self.actionRecherche_par_num_ro_d_inscription_2.setText(_translate("MainWindow", "Recherche par numéro d\'inscription"))
        self.actionRecherche_par_section_et_niveau_2.setText(_translate("MainWindow", "Recherche par section et niveau"))
        self.actionRecherche_par_num_ro_d_inscription_et_semestre.setText(_translate("MainWindow", "Recherche par numéro d\'inscription et semestre"))
        self.actionBulletin_de_note_d_un_etudiant.setText(_translate("MainWindow", "Bulletin de note d\'un étudiant"))
        self.actionBulletin_de_note_d_un_tudiant_par_semestre.setText(_translate("MainWindow", "Bulletin de note d\'un étudiant par semestre"))
        self.actionEtudiants_admis_d_une_section_donnee.setText(_translate("MainWindow", "Etudiants admis d\'une section donnée"))
        self.actionEtudiants_redoublants_d_une_section_donnee.setText(_translate("MainWindow", "Etudiants redoublants d\'une section donnée"))
        self.actionEtudiants_admis_de_l_ISIMM.setText(_translate("MainWindow", "Etudiants admis de l\'ISIMM"))
        self.actionEtudiants_redoublants_de_l_ISIMM.setText(_translate("MainWindow", "Etudiants redoublants de l\'ISIMM"))
        self.actionMoyennes_des_etudiants_d_une_section_donnee.setText(_translate("MainWindow", "Moyennes des étudiants d\'une section donnée"))
        self.actionEnregistrement_fichier_Etudiants.setText(_translate("MainWindow", "Enregistrement fichier Etudiants"))
        self.actionRecuperation_fichier_Etudiants.setText(_translate("MainWindow", "Récupération fichier Etudiants"))
        self.actionEnregistrement_fichier_Matieres.setText(_translate("MainWindow", "Enregistrement fichier Matières"))
        self.actionRecuperation_fichier_Matieres.setText(_translate("MainWindow", "Récupération fichier Matières"))
        self.actionEnregistrement_fichier_Notes.setText(_translate("MainWindow", "Enregistrement fichier Notes"))
        self.actionRecuperation_fichier_Notes.setText(_translate("MainWindow", "Récupération fichier Notes"))
